### PR TITLE
Change 'raise' action text on identity change

### PR DESCRIPTION
**Pull request by f1u77y**
I know QML not so good but it seems to be ugly. Tell me if you know better solution please.

### CODE REVIEW

**Comment by audoban** [comment]
Why do you consider it necessary to open the player, when the source player changes?

**Comment by f1u77y** [comment]
I don't consider this necessary. I just want the caption "Open your-player-name" to match the current player name even if it's changed in runtime.

**Comment by audoban** [comment]
im so sorry, do you have reason. The caption should match with the current media player.

**Comment by audoban** [comment]
However, I thought that I had already covered that problem:

https://github.com/audoban/PlayBar2/blob/82d3f7a453420d34561171795667a532aec2fe1b/plasmoid/contents/ui/main.qml#L255-L278

You can give me some situation where the caption of the action does not match the name of current media player.

**Comment by audoban** [comment]
Please use the branch *newfeatures*, this problem should have been solved.

**Comment by f1u77y** [comment]
Yes, that was fixed, thanks!

Sorry for delay.

**Pull request closed without merging**
